#注释
#1-字典格式,冒号后加空格
#name: tom #名字，需要加空格，字符串不用加引号
##age: 20 #年龄，需要加空格
#- #2-列表
#  - 灰色
#  - 0
#  - test

###3-复合结构 列表包含字典
#- name: tom
#  age: 30
#  data:
#- info: heool
##4-字典中包含列表
#info:
#  - 10
#  - 20
#  - 30
#data:
#  - 100
#  - 200
#  - 300
##5-字典套字典
#info:
##  name: tom
##  age: 90
##data:
##  data1: 10
###  data2: 30
###6-引号的处理;1)单引号的特殊字符会被转义，也就是原样输出，双引号不会被转义，会输出特殊字符如：\n
###如果数据的整形要求是字符串，那么必须加双引号
##info: helloworld
##info2: "hello\nworld"
#
#--- #分隔符  分割多个yaml文件
#info:
#  - 10

#  - 20
#  - 30
#---
#data:
#  - 100
#  - 200
#  - 300
host: &host 192.168.0.1
url: *host
